import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { TokenContext } from '../components/keycloak'
import React from 'react'

export default function Home() {
  const token = React.useContext(TokenContext)

  console.log('We got the token in the component', token)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a>
        </h1>

        <p className={styles.description}>Your registered name is {token.info.name}</p>
      </main>
    </div>
  )
}
